config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get  'comfirmation'
    end
    
    resources :attendances, only: [:edit, :update] do
     member do  
       get 'lunch_check'
       patch 'update_lunch_check'
     end   
     collection do
        get 'lunch_check_info'
        patch 'update_lunch_check_info'   
     end #collection do end
    end #resouces do end
  end #user resouces do end 
end
#draw do end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
   # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  require 'line/bot'#gem読み込み
  UPDATE_ERROR_MSG = "登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "給食の時間です！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end


  def lunch_check #アレルギーチェック
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    @superiors = User.where(superior: true).where.not(id: @user.id)
  end
 
  def update_lunch_check
  #アレルギーチェックのアップデート
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if params[:attendance][:first_teacher] == "0" || params[:attendance][:second_teacher] == "0" || params[:attendance][:student] == "0"
      flash[:danger] = "#{@user.name}さん,チェックをすべてしてください。 "
    elsif params[:attendance][:lunch_check_superior].blank? 
      flash[:danger] = "アレルギー担当者を選択して下さい。 "
    else  
       # 更新時の処理
      params[:attendance][:status] = "報告中"
      @attendance.update_attributes(lunch_check_params)
      flash[:success] = "#{@user.name}さんがアレルギーチェックをしました。"
    end 
    redirect_to user_url(@user)   
  end
 
  def lunch_check_info 
    @user = User.find(params[:user_id])
    @requesters = Attendance.where(lunch_check_superior: @user.name, status: "報告中").order(:user_id).group_by(&:user_id)
  end 
 
  def update_lunch_check_info
    @user = User.find(params[:user_id])
    ActiveRecord::Base.transaction do 
      lunch_check_info_params.each do |id, item|
        if item[:superior_checker] == "1"
          attendance = Attendance.find(id)
          attendance.update_attributes!(item)
          @info_sum = Attendance.where(status: "確認済").count
          @unapproval_info_sum = Attendance.where(status: "要再確認").count
          flash[:success] = "確認済#{@info_sum}件、要再確認#{@unapproval_info_sum}件"
          test
        end #if end 
      end #each end 
      redirect_to user_url(@user)
    end #Acctive do end    
 #def end
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
  end #def end require 'line/bot'
 
  def test
    message = {
        type: 'text',
        text: "アレルギーチェックが行われました" #送られた内容をそのまま返す
    } 
     
    client ||= Line::Bot::Client.new { |config|
      config.channel_secret = "9b4e4731db8a314b562712c3c8cf1c54"
      config.channel_token = "/LhqzVxk6YuA5655YZBg8/7yhymmMegyBkGyr1y6Y6+v6O0cg5DWy6JfXWtb9YDr7zSDnqqAdwIxLXdSACnwxcxvZOiCk561cIdccN9vjKlYRNt6wio/TVtctbkyzCOpLe6H3s0CuQdzGxe3FBVrQgdB04t89/1O/w1cDnyilFU="
    }
    # 応答メッセージを送る
    client.broadcast(message)
  end
  

private

  def lunch_check_params
    params.require(:attendance).permit(:first_teacher, :second_teacher, :student, :lunch_check_superior, :status, :note)  
  end 
  
  def lunch_check_info_params 
    params.require(:user).permit(attendances: [:status, :superior_checker])[:attendances]
  end  
  
  
end  

app/helpers/attendances_helper.rb
module AttendancesHelper
   def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '開始' if attendance.started_at.nil?
      return '終了' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    false
   end    
end

app/views/attendances/_lunch_check.html.erb
<% provide(:class_text, 'lunch_check') %>
<% provide(:button_text, '給食チェック') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">【アレルギーチェック】</h1>
    </div>
    
    <div class="modal-body">
    <%= form_with(model: @attendance, url: update_lunch_check_user_attendance_path(@user, @attendance), local: true, method: :patch) do |f| %>   
    <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>第１チェック</th>
          <th>第2チェック</th>
          <th>本人</th>
          <td>備考</td>
          <th>アレルギー担当確認</th>
        </tr>
      </thead>
       
　    <tbody>
　       <% 
            css_class = 
            case %w{日 月 火 水 木 金 土}[@attendance.worked_on.wday]
            when '土'
              'text-primary'
            when '日'
              'text-danger'
            end
          %> 
        <tr> 
          <td><%= l(@attendance.worked_on, format: :short) %></td>
          <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[@attendance.worked_on.wday] %></td>
          <td><%= f.check_box :first_teacher, class: "form-control" %></td>
          <td><%= f.check_box :second_teacher, class: "form-control" %></td>
          <td><%= f.check_box :student, class: "form-control" %></td>
          <td><%= f.text_field :note, class: "form-control" %></td>
           <td><%= f.collection_select :lunch_check_superior, @superiors, :name, :name, :include_blank => true %></td>
        </tr> 
       </tbody>    
        
      </table> 
      <%= f.submit "アレルギーチェックを報告", class: "btn btn-primary btn-lg btn-block" %></div> 
      <% end %>
  　 </div> 
 　 </div> 
 </div>  
    
      
     
        
            
            
                  
            

app/views/attendances/_lunch_check_info.html.erb
<% provide(:class_text, 'lunch_check_info') %>
<% provide(:button_text, '給食チェック') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    
    <div class="modal-body">
      <%= form_with(model: @user, url: update_lunch_check_info_user_attendances_path(@user), local: true, method: :patch) do |f| %>   
        <% @requesters.each do |user_id, attendances| %>
         <h1 class="modal-title">【<%= "#{User.find(user_id).classroom}" %>からアレルギーチェック報告】</h1>
          <table  border=2 width=100%, class="table table-bordered table-condensed user-table">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>学級</th>
                <td>備考</td>
                <th>チェック</th>
                <th>アレルギー担当確認</th>
                <th></th>
              </tr>
            </thead>
            <% attendances.each do |day| %>
              <%= f.fields_for "attendances[]", day do |at| %> 
        　       <tbody>
          　         <% 
                      css_class = 
                      case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
                      when '土'
                        'text-primary'
                      when '日'
                        'text-danger'
                      end
                    %> 
                    <tr> 
                      <td><%= l(day.worked_on, format: :short) %></td>
                      <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
                      <td><%= User.find(user_id).classroom %></td>
                      <td><%= day.note  %></td>
                      <td><%= at.check_box :superior_checker, class: "form-control" %></td>
                      <td><%= at.select :status, [' ', '要再確認', '報告中', '確認済'], class: "form-control" %></td>
                      <td><%= link_to "確認",comfirmation_user_path(user_id, day: day.worked_on), class: "btn btn-primary btn-lg btn-block" %></td>
                    </tr> 
                 </tbody>    
              <% end %>
            <% end %>

          </table> 
        <% end %>
      <%= f.submit "アレルギーチェックを確認しました", class: "btn btn-primary btn-lg btn-block" %></div> 
      <% end %>
  　 </div> 
 　 </div> 
 </div>  
    
      
     
        
            
            
                  
            

app/views/attendances/lunch_check.js.erb
$("#lunch-check").html("<%= escape_javascript(render 'lunch_check') %>");
$("#lunch-check").modal("show");

app/views/attendances/lunch_check_info.js.erb
$("#lunch-check-info").html("<%= escape_javascript(render 'lunch_check_info') %>");
$("#lunch-check-info").modal("show");